label_1:
  type: QLabel
  width: 300
  height: 100
  alignment: center
  fontFamily: times
  fontPoint: 40
  fontBold: True
  text: test

label_2:
  type: QLabel
  width: 300
  height: 100
  alignment: center
  fontFamily: times
  fontPoint: 40
  fontBold: True
  box: 1
  text: test

label_3:
  type: QLabel
  width: 300
  height: 100
  alignment: center
  fontFamily: times
  fontPoint: 40
  fontBold: True
  box: 2
  text: test

label_4:
  type: QLabel
  width: 300
  height: 100
  alignment: center
  fontFamily: times
  fontPoint: 40
  fontBold: True
  box: 3
  text: test

slider_1:
  type: QSlider
  orientation: h #(h or v)
  max: 50
  min: 0
  default: 25


#label:
#  type: QLabel
#  width: 300
#  height: 100
#  alignment: center
#  fontFamily: times
#  fontPoint: 40
#  fontBold: True
#  box: 1  #(1 or 2 or 3)
#  text: start

#button:
#  type: QPushButton
#  width: 200
#  height: 100
#  fontFamily: times
#  fontPoint: 40
#  fontBold: False
#  text: start

#slider:
#  type: QSlider
#  orientation: h  #(h or v)
#  max: 100
#  min: 0
#  default: 50
