#label:
#  type: QLabel
#  width: 300
#  height: 100
#  alignment: center
#  fontFamily: times
#  fontPoint: 40
#  fontBold: True
#  linewidth: 5
#  shape: box #(box or panel)
#  shadow: raised #(plain or raised or sunken)
#  text: start
#  color: red
#  background-color: yellow

#button:
#  type: QPushButton
#  width: 200
#  height: 100
#  fontFamily: times
#  fontPoint: 40
#  fontBold: False
#  text: start

#slider:
#  type: QSlider
#  orientation: h  #(h or v)
#  max: 100
#  min: 0
#  default: 50
#  tickposition: both #(both, above, below, left, right)