slider_1:
  type: QSlider
  orientation: h  #(h or v)
  max: 4
  min: 0
  default: 2

slider_2:
  type: QSlider
  orientation: h  #(h or v)
  max: 4
  min: 0
  default: 2
  tickposition: above  #(above, below, left, right, both)  

slider_3:
  type: QSlider
  orientation: h  #(h or v)
  max: 4
  min: 0
  default: 2
  tickposition: below  #(above, below, left, right, both)  

slider_4:
  type: QSlider
  orientation: h  #(h or v)
  max: 4
  min: 0
  default: 2
  tickposition: both  #(above, below, left, right, both)  

slider_5:
  type: QSlider
  orientation: v  #(h or v)
  max: 4
  min: 0
  default: 2

slider_6:
  type: QSlider
  orientation: v  #(h or v)
  max: 4
  min: 0
  default: 2
  tickposition: left  #(above, below, left, right, both)  

slider_7:
  type: QSlider
  orientation: v  #(h or v)
  max: 4
  min: 0
  default: 2
  tickposition: right  #(above, below, left, right, both)  

slider_8:
  type: QSlider
  orientation: v  #(h or v)
  max: 4
  min: 0
  default: 2
  tickposition: both  #(above, below, left, right, both)  

#label:
#  type: QLabel
#  width: 300
#  height: 100
#  alignment: center
#  fontFamily: times
#  fontPoint: 40
#  fontBold: True
#  linewidth: 5
#  shape: box #(box or panel)
#  shadow: raised #(plain, raised or sunken)
#  text: start

#button:
#  type: QPushButton
#  width: 200
#  height: 100
#  fontFamily: times
#  fontPoint: 40
#  fontBold: False
#  text: start

#slider:
#  type: QSlider
#  width: 200
#  height: 100
#  orientation: h  #(h or v)
#  max: 100
#  min: 0
#  default: 50
#  tickposition: above  #(above, below, left, right or both)  