label_1:
  type: QLabel
  width: 300
  height: 100
  alignment: center
  fontFamily: times
  fontPoint: 40
  fontBold: True
  text: test
  linewidth: 10

#label:
#  type: QLabel
#  width: 300
#  height: 100
#  alignment: center
#  fontFamily: times
#  fontPoint: 40
#  fontBold: True
#  box: 1  #(1 or 2 or 3)
#  linewidth: 5
#  text: start

#button:
#  type: QPushButton
#  width: 200
#  height: 100
#  fontFamily: times
#  fontPoint: 40
#  fontBold: False
#  text: start

#slider:
#  type: QSlider
#  orientation: h  #(h or v)
#  max: 100
#  min: 0
#  default: 50