label_1:
  type: QLabel
  width: 300
  height: 100
  alignment: center
  fontFamily: times
  fontPoint: 40
  fontBold: True
  text: start

label_2:
  type: QLabel
  width: 300
  height: 100
  alignment: center
  fontFamily: times
  fontPoint: 40
  fontBold: True
  linewidth: 10 
  shape: box #(box or panel)
  shadow: plain #(plain or raised or sunken)
  text: start

label_3:
  type: QLabel
  width: 300
  height: 100
  alignment: center
  fontFamily: times
  fontPoint: 40
  fontBold: True
  linewidth: 10 
  shape: box #(box or panel)
  shadow: raised #(plain or raised or sunken)
  text: start

label_4:
  type: QLabel
  width: 300
  height: 100
  alignment: center
  fontFamily: times
  fontPoint: 40
  fontBold: True
  linewidth: 10 
  shape: box #(box or panel)
  shadow: sunken #(plain or raised or sunken)
  text: start

label_5:
  type: QLabel
  width: 300
  height: 100
  alignment: center
  fontFamily: times
  fontPoint: 40
  fontBold: True
  linewidth: 10 
  shape: panel #(box or panel)
  shadow: plain #(plain or raised or sunken)
  text: start

label_6:
  type: QLabel
  width: 300
  height: 100
  alignment: center
  fontFamily: times
  fontPoint: 40
  fontBold: True
  linewidth: 10 
  shape: panel #(box or panel)
  shadow: raised #(plain or raised or sunken)
  text: start

label_7:
  type: QLabel
  width: 300
  height: 100
  alignment: center
  fontFamily: times
  fontPoint: 40
  fontBold: True
  linewidth: 10 
  shape: panel #(box or panel)
  shadow: sunken #(plain or raised or sunken)
  text: start

#label:
#  type: QLabel
#  width: 300
#  height: 100
#  alignment: center
#  fontFamily: times
#  fontPoint: 40
#  fontBold: True
#  linewidth: 5
#  shape: box #(box or panel)
#  shadow: raised #(plain or raised or sunken)
#  text: start

#button:
#  type: QPushButton
#  width: 200
#  height: 100
#  fontFamily: times
#  fontPoint: 40
#  fontBold: False
#  text: start

#slider:
#  type: QSlider
#  orientation: h  #(h or v)
#  max: 100
#  min: 0
#  default: 50